### ISSUE TITLE
逻辑不对

### ISSUE THREAD

**Issue by jsjtwty** [myseil/smzdm_sgin#1]
https://github.com/myseil/smzdm_sgin/blob/d2f50b97fcc2308490dd05a16f9c2871e2538725/smzdm.py#L31
- 31行这里的False应该改成True，不然执行不了签到
- 如果在签到完成的提示信息中添加连签天数会发现连签天数少一天
- 运行之后网页端签到完成，经验也增加了但APP端查看仍然提示签到。仔细看data发现张大妈的签到分三个部分：网页、APP、微信，单单运行这个脚本只能够进行网页端的签到。可否完成APP的签到使之与网页端同步。

**Comment by myseil** [comment]
额，初学Python。感谢建议！

意见修改了，这个分网页，APP，微信签到的这个确实是纯在问题，目前只能网页签到，但是我发现只要网页签到后，APP不签到也是可以的！
