### ISSUE TITLE
请问userCookie那里填的是哪个字符串呀？

### ISSUE THREAD

**Issue by zhaopeilin1** [myseil/smzdm_sgin#3]
请问userCookie那里填的是哪个字符串呢
通过f12抓请求之后，发现cookie里好多字段。比如 user ：user%3A8302671999%7C830267xxx  
 smzdm_id:**********
PHPSESSID:xxxxxxx
项目里到底填的是哪个字段呢？不会弄。请大佬详细教一下
--

**Comment by myseil** [comment]
userCookie = "sess=*; user=user:*|*; smzdm_id=*;"  我自己填写的这三个字段就可以了！
