### ISSUE TITLE
小白问问题，关于checkin，不是很懂代码

### ISSUE THREAD

**Issue by uoow** [myseil/smzdm_sgin#4]
请教一下，代码里好像没有做什么操作就算签到了，是不是可以认为，只要访问了checkin_url = 'https://zhiyou.smzdm.com/user/checkin/jsonp_checkin'，这个地址，就是签到了？这个地址里服务器会做一些操作？？
另外，checkin = req(checkin_url)['data']，这一句是调用req的函数，那后面的['data']又是什么用法？

**Comment by myseil** [comment]
> 请教一下，代码里好像没有做什么操作就算签到了，是不是可以认为，只要访问了checkin_url = '[https://zhiyou.smzdm.com/user/checkin/jsonp_checkin'，这个地址，就是签到了？这个地址里服务器会做一些操作？？](https://zhiyou.smzdm.com/user/checkin/jsonp_checkin'%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%B0%B1%E6%98%AF%E7%AD%BE%E5%88%B0%E4%BA%86%EF%BC%9F%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E9%87%8C%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BC%9A%E5%81%9A%E4%B8%80%E4%BA%9B%E6%93%8D%E4%BD%9C%EF%BC%9F%EF%BC%9F)
> 另外，checkin = req(checkin_url)['data']，这一句是调用req的函数，那后面的['data']又是什么用法？

是的只要访问这个网址就算签到了，checkin = req(checkin_url)['data']这里是获取一个['data']里面的集合赋值到checkin，通过看代码第39行就知道了！
