### ISSUE TITLE
运行出现报错

### ISSUE THREAD

**Issue by feixu0530** [myseil/smzdm_sgin#7]
我最近执行出现报错，不知道是否是什么值得买的环境出现变化导致的：
Traceback (most recent call last):
  File "/sh/smzdm.py", line 45, in <module>
    info = '签到信息 %s 目前积分：%s，增加积分：%s，经验值：%s，金币：%s，威望：%s，等级：%s' % (data['nickname'], checkin['point'], checkin['add_point'], checkin['exp'], checkin['gold'], checkin['prestige'], checkin['rank'])
TypeError: list indices must be integers or slices, not str

**Comment by myseil** [comment]
> 我最近执行出现报错，不知道是否是什么值得买的环境出现变化导致的： Traceback (most recent call last): File "/sh/smzdm.py", line 45, in info = '签到信息 %s 目前积分：%s，增加积分：%s，经验值：%s，金币：%s，威望：%s，等级：%s' % (data['nickname'], checkin['point'], checkin['add_point'], checkin['exp'], checkin['gold'], checkin['prestige'], checkin['rank']) TypeError: list indices must be integers or slices, not str

Python不支持str和int的拼接，可以将所有的json值全部str。
然后，现在值得买经常提示输入验证码，这个都已经好久没有维护了！
推荐一个签到框架 https://github.com/qiandao-today/qiandao/ 是我目前在使用的！
